services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: minab123
      POSTGRES_USER: minabuser
      POSTGRES_DB: minabdb
    ports:
      - "5432:5432"

  hasura:
    image: hasura/graphql-engine:v2.36.1
    ports:
      - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://minabuser:minab123@postgres:5432/minabdb?sslmode=disable
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: mysecretadmin

  go-backend:
    build: ./go-backend # Assuming your Go code is in this directory
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - HASURA_GRAPHQL_ENDPOINT=http://hasura:8080
      - HASURA_GRAPHQL_ADMIN_SECRET=mysecretadmin
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
